---
- name: Detectar pods caídos en OpenShift
  hosts: localhost
  sources:
    - name: Obtener estado de los pods
      ansible.eda.generic:
        module: kubernetes.core.k8s_info
        kind: Pod
        namespace: "aap"  # Cambia esto según el namespace deseado
  rules:
    - name: Detectar pod en estado de error
      condition: >
        any(resource.status.phase in ['Failed', 'CrashLoopBackOff'] for resource in event.resources)
      action:
        run_job_template:
          name: os-test
          organization: Default
