---
- name: Monitorizar una URL y ejecutar un Job Template
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls:
          - "192.168.6.70:32032"
        delay: 10  # Comprobación cada 10 segundos
  rules:
    - name: Ejecutar job si la URL responde con 200
      condition: event.status == 200
      action:
        run_job_template:
          name: "ip-test"
          organization: "Default"
