---
- name: Kubernetes Pod Monitor
  hosts: all
  sources:
    - ansible.eda.kubernetes:
        namespace: aap  # Ajusta el namespace según tu necesidad
        state: ["Failed", "CrashLoopBackOff"]
  rules:
    - name: Detectar pods en estado crítico
      condition: event.kubernetes.object.status.phase in ["Failed", "CrashLoopBackOff"]
      action:
        run_job_template:
          name: os-test
          organization: Default
