---
- name: Check OS Version Rulebook
  hosts: localhost
  sources:
    - name: Listen for OS Check Requests
      ansible.eda.range:
        limit: 10
  rules:
    - name: Get OS Version
      condition: event.meta is defined
      action:
        run_job_template:
          name: os-test
          organization: Default
