---
- name: Check OS Version Rulebook
  hosts: localhost
  sources:
    - name: Listen for OS Check Requests
      ansible.eda.range:
        limit: 10
  rules:
    - name: Detectar pod en estado de error
      condition: event.resources | selectattr('status.phase', 'in', ['Failed', 'CrashLoopBackOff']) | list | length > 0
      action:
        run_job_template:
          name: os-test
          organization: Default
