---
- name: Comprobar disponibilidad de una página web
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls:
          - "http://192.168.6.70:32032/"
        delay: 10  # Revisa cada 30 segundos
 
  rules:
    - name: Página web disponible
      condition: event.status == 200
      action:
        run_job_template:
          name: disponible
          organization: Default
 
    - name: Página web caída
      condition: event.status != 200
      action:
        run_job_template:
          name: fallo
          organization: Default
